### PR TITLE
Add flag enableRunRoutes

### PR DESCRIPTION
**Pull request by YChebotaev**
Add flag to disable runRoutes as discussed at https://github.com/sw-yx/react-netlify-identity/pull/13#issuecomment-502415634

### CODE REVIEW

**Comment by YChebotaev** [comment]
@sw-yx Hey? Any comment?

**Comment by sw-yx** [comment]
hey! sorry been busy. looking at this now

**Comment by sw-yx** [comment]
hey! sorry been busy. looking at this now

**Comment by sw-yx** [comment]
done! cheers!

**Comment by YChebotaev** [comment]
Cool! Thanks You!

**Pull request merged**
